### ISSUE TITLE
Serious problem in Readme file for csgo-data repository

### ISSUE THREAD

**Issue by miifanboy** [IgaoGuru/Sequoia#2]
It says that you should launch csgo with -untrusted flag but -untrusted flag doesn't launch your game without vac it enables signed dll injection for apps like discord , nvidia shadowplay etc. The right flag to disable vac is -insecure. You should change this ASAP since it can cause some people to get VAC banned.

**Comment by IgaoGuru** [comment]
Wow! I hadn't realized. Thank you. Just updated the readme
