### ISSUE TITLE
May I ask for which yolov5 version are the sequoiaV1.pt file used been train.

### ISSUE THREAD

**Issue by Jerry-zirui** [IgaoGuru/Sequoia#3]
I wanna convert the model  so that it may run on tensorRT.

**Comment by IgaoGuru** [comment]
Hi! 

SequoiaV1.pt is a trained **yolov5s**.
You can check that by [counting the number of parameters in the model](https://stackoverflow.com/questions/49201236/check-the-total-number-of-parameters-in-a-pytorch-model)! (In this case, 7.2 M)
